Repository vi2920va/FE_interview, pull requests merged in 2022-04, with the labels that each got.

#123 [15주차] [주현] React - React-router-dom
  React/React-router-dom.md
Labels: Status: Accepted

#117 [15주차] [두현] Network - TCP_IP_1
  Network/TCP_IP_1.md
Labels: Status: 리뷰 요청

#127 [15주차] [남은] JavaScript - 프로토타입 상속
  JavaScript/프로토타입상속.md
Labels: Status: Accepted

#129 Javascript - 일급함수
  JavaScript/일급함수.md
Labels: Status: Accepted

#126 [16주차] [송현] CS - 프로세스와 쓰레드 작성
  CS/Procsess_Thread.md
  CS/README.md
  Git/Git-Flow.md
Labels: Status: Accepted

#131 [16주차] [수민] React - React Test 내용 추가
  React/React-Test.md
Labels: Status: Accepted

#130 [16주차] [남은] React - Version 18 Summary
  React/Version-18-Summary.md
Labels: Status: Accepted

#135 [17주차][남은] FrontEnd - 프론트엔드 개발환경의 이해
  FrontEnd/프론트엔드개발환경.md
Labels: Status: 현재 진행 중

#134 [17주차] [송현] CS - 멀티프로세스 브라우저의 아키텍쳐
  CS/Multi-Process.md
Labels: Status: Accepted

#128 [17주차] [주현] React - React.PureComponent
  React/React-rendering optimization.md
Labels: Status: Accepted

#136 [17주차] [수민] TypeScript - basic types
  TypeScript/Types.md
Labels: Status: Accepted

#142 [18주차][주현] React - state management
  React/React-StateManagement.md
Labels: Status: Accepted

#141 [18주차][수민] typescript: unknown/never/any
  TypeScript/Unkown-never-any.md
Labels: Status: Accepted

#140 [18주차][송현] CS - Package Manage (npm / yarn)
  FrontEnd/Package-Manager.md
Labels: Status: Accepted

#139 [18주차][수민] JavaScript - Intersection Observer API
  JavaScript/Intersection-Observer-API.md
Labels: Status: Accepted

#138 [18주차][남은] Network - HTTP Header
  Network/HTTP-Header.md
Labels: Status: 수정 요청
